
package com.example.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentService", targetNamespace = "http://service.example.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.example.com/StudentService/addStudentRequest", output = "http://service.example.com/StudentService/addStudentResponse")
    public boolean addStudent(
        @WebParam(name = "arg0", partName = "arg0")
        Student arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.example.com/StudentService/deleteStudentRequest", output = "http://service.example.com/StudentService/deleteStudentResponse")
    public boolean deleteStudent(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.service.Student
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.example.com/StudentService/getStudentRequest", output = "http://service.example.com/StudentService/getStudentResponse")
    public Student getStudent(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns com.example.service.StudentArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.example.com/StudentService/getAllStudentsRequest", output = "http://service.example.com/StudentService/getAllStudentsResponse")
    public StudentArray getAllStudents();

}
